/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package floodFill;

import java.awt.Graphics;


/**
 *
 * @author FilPag 
 */
public class floodFillJPanel extends javax.swing.JPanel {

    Board board = new Board();
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
            board.draw(g);
            board.setSize(cbSize.getSelectedIndex());
        
    }

    /**
     * Creates new form floodFillJPanel
     */
    public floodFillJPanel() {
        initComponents();
        board.generateColors();
        lblMoves.setText("Moves: " + Integer.toString(board.moves) + "/"
                + Integer.toString(board.maxMoves));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnNewgame = new javax.swing.JButton();
        lblMoves = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        cbSize = new javax.swing.JComboBox();
        lblSize = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(700, 700));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        btnNewgame.setText("New Game");
        btnNewgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewgameActionPerformed(evt);
            }
        });

        lblMoves.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMoves.setText("Placeholder");
        lblMoves.setToolTipText("");
        lblMoves.setMaximumSize(new java.awt.Dimension(256, 43));

        lblDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescription.setText("Click cells. Fill the board with a single color.");

        cbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12x12", "16x16", "20x20", "24x24" }));
        cbSize.setSelectedIndex(2);

        lblSize.setText("Size:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblMoves, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewgame, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewgame)
                    .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSize)
                    .addComponent(lblMoves, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(634, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        try {
            board.floodFill(0, 0, board.getColor(evt.getX(),
                    evt.getY()), board.color[0][0]);
            repaint();
        } catch (java.lang.ArrayIndexOutOfBoundsException error) {
        }
        lblMoves.setText("Moves: " + Integer.toString(board.moves) + "/"
                + Integer.toString(board.maxMoves));
        if (board.win()) {
            lblMoves.setText("You win!");
        } else if (board.moves >= board.maxMoves) {
            lblMoves.setText("You lose!");
        }

    }

    private void btnNewgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewgameActionPerformed
        board.generateColors();
        board.moves = 0;
        lblMoves.setText("Moves: " + Integer.toString(board.moves) + "/"
                + Integer.toString(board.maxMoves));
        repaint();
    }

    private javax.swing.JButton btnNewgame;
    private javax.swing.JComboBox cbSize;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblMoves;
    private javax.swing.JLabel lblSize;
}
